Repository frontendcafe/cmyk-mango, pull requests merged in 2021-09, with the labels that each got.

#11 Reestructuración del proyecto
  package-lock.json
  package.json
  public/index.html
  src/app.js
  src/pages/index.js
  src/pages/login/login.js
  src/pages/primeros-pasos/primeros-pasos.js
  src/pages/registro/registro.js
Labels: frontend

#12 Reestructuración del proyecto v2
  .gitignore
  css/index.css
  css/login.css
  css/primeros-pasos.css
  css/registro.css
  index.html
  js/index.js
  js/login.js
  js/primeros-pasos.js
  js/registro.js
  package-lock.json
  package.json
  src/pages/login/login.js
  src/pages/registro/registro.js
Labels: frontend

#32 Install Prettier
  .husky/pre-commit
  .prettierignore
  .prettierrc.json
  css/index.css
  css/login.css
  css/navegacion.css
  css/primeros-pasos.css
  css/reunion.css
  index.html
  js/index.js
  js/login.js
  js/navegacion.js
  js/primeros-pasos.js
  navegacion.html
  package-lock.json
  package.json
  reunion.html
Labels: frontend

#34 Agregar API de autenticación y de reuniones
  .gitignore
  index.html
  js/api/auth.js
  js/api/index.js
  js/api/meetings.js
Labels: backend

#48 Install y configure dayjs
  index.html
  js/dayjs-config.js
Labels: frontend

#49 Add derived values for getMeeting
  js/api/meetings.js
Labels: frontend

#50 Add spanish support for dayjs
  index.html
  js/dayjs-config.js
Labels: frontend

#51 Format meeting in getMeetings
  js/api/meetings.js
Labels: frontend

#59 fix: add div with id no-meeting
  index.html
Labels: bug, frontend

#62 feat: add firebase config
  .gitignore
  js/api/firebase-config.js
  js/api/index.js
Labels: frontend

#68 feat: add register form logic
  js/index.js
  js/registro.js
Labels: frontend

#69 feat: new meeting
  descripcion.html
  nueva-reunion.html
Labels: frontend

#70 feat: refactor navbar
  acerca-de.html
  confirmacion.html
  css/confirmacion.css
  css/fecha.css
  css/invitation.css
  invitation.html
  js/navegacion.js
  navegacion.html
  nueva-reunion.html
  reunion.html
  reuniones.html
  votaciones.html
Labels: frontend

#73 fix: makes image shorter
  css/reunion.css
  css/votaciones.css
Labels: frontend

#74 ajustes del diseño de Reunion.html
  README.md
  css/reunion.css
Labels: frontend
